language: rust
rust: nightly
cache:
  directories:
    - ~/.cargo/registry
env:
  global:
    - MOZ_HEADLESS=1
addons:
  firefox: latest

env:
  matrix:
    - DEV_FLAG="--dev" RUST_DIST="stable"
    - DEV_FLAG="--release" RUST_DIST="stable"
    - DEV_FLAG="--dev" RUST_DIST="beta"
    - DEV_FLAG="--release" RUST_DIST="beta"
    - DEV_FLAG="--dev" RUST_DIST="nightly"
    - DEV_FLAG="--release" RUST_DIST="nightly"

install:
  - "export RUSTFLAGS=$(cargo --version | grep nightly >/dev/null && echo \"-Z external-macro-backtrace\")"
  - "rustup default $RUST_DIST"
  - "rustup component add rustfmt --toolchain $(rustup show active-toolchain | cut -d\" \" -f1)"
  - cargo install just wasm-pack
  - just npm

script:
  - just dev="$DEV_FLAG" check build
  - cargo test --all
  - cargo fmt --all -- --check

after_success:
  - "stat target/wasm32-unknown-unknown/*/eviov_client.wasm"

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: client/site/dist
  on:
    branch: master
    condition: '"${RUST_DIST} ${DEV_FLAG}" = "nightly --release"'
