language: rust
rust: nightly
cache:
  directories:
    - ~/.cargo
env:
  global:
    - MOZ_HEADLESS=1
addons:
  firefox: latest

env:
  matrix:
    - DEV_FLAG="--dev"
    - DEV_FLAG="--release"

install:
  - "export RUSTFLAGS=$(cargo --version | grep nightly >/dev/null && echo \"-Z external-macro-backtrace\")"
  - "rustup component add rustfmt --toolchain $(rustup show active-toolchain | cut -d\" \" -f1)"
  - command -v just || cargo install just
  - command -v wasm-pack || cargo install wasm-pack
  - just npm

script:
  - just dev="$DEV_FLAG" check build
  - cargo test --all
  - cargo fmt --all -- --check

after_success:
  - "stat target/wasm32-unknown-unknown/*/eviov_client.wasm"

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: client/site/dist
  on:
    branch: master
    condition: '"${DEV_FLAG}" = "--release"'
