[workspace]
members = [
	"codegen",
	"types",
	"proto",
	"context",
	"transport",
	"common",
	"client",
	"server",
	"games/*/"
]

[profile.release]
opt-level = 3 # change to "s" or "z" when we need to
panic = "abort"
lto = true
