[package]
name = "eviov-server"
version = "0.0.0"
authors = ["SOFe <sofe2038@gmail.com>"]
edition = "2018"
license = "AGPL-3.0"
repository = "https://github.com/SOF3/eviov"
homepage = "https://github.com/SOF3/eviov"
readme = "README.md"
description = "Orbital shooters game"

[dependencies]
actix = "0.9.0"
actix-rt = "1.0.0"
actix-web = "2.0.0"
actix-web-actors = "2.0.0"
dirmod = "0.2.0-alpha.1"
eviov = {path = ".."}
futures = "0.3.1"
log = "0.4.8"
pretty_env_logger = "0.3.1"
rmp-serde = "0.14.0"
