name: Client Pages Deployment
on:
  push:
    branches:
      - master
jobs:
  build:
    name: WASM build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rustup_channel:
          - nightly
        wasm_dev_flag:
          - "--release"
    steps:
      - uses: actions/checkout@v2
      - name: rustup install
        run: |
          rustup toolchain update --no-self-update ${{ matrix.rustup_channel }}
          rustup default ${{ matrix.rustup_channel }}
      - name: install wasm-pack
        run: cargo install wasm-pack
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm install -g wasm-opt
      - name: npm install
        run: npm install
        working-directory: client/site
      - name: Build WASM
        run: wasm-pack build ${{ matrix.wasm_dev_flag }}
        working-directory: client
      - name: Build distributable
        run: npm run build
        working-directory: client/site
      - name: Build docs
        run: cargo doc --all --document-private-items
      - name: Deploy
        run: |
          mkdir stage
          pushd stage
          cp -r ../client/site/dist/* .
          cp -r ../target/doc doc
          cp ../LICENSE LICENSE
          popd
          git clone https://${{ secrets.GH_TOKEN }}@github.com/eviov/eviov.github.io _pages
          cd _pages
          git rm -r .
          cp -r ../stage/* .
          git add .
          git -c "user.name=SOFe" -c "user.email=sofe2038@gmail.com" commit -m "Pages deployed for eviov/eviov@${{github.sha}}"
          git push
