name: Rust CI
on:
  - push
  - pull_request
jobs:
  fmt:
    name: rustfmt check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: rustup install
        run: |
          rustup toolchain update --no-self-update nightly
          rustup default nightly
          rustup component add rustfmt
      - name: Format check
        run: cargo fmt --all -- --check
  build:
    name: Rust build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rustup_channel:
          - nightly
        dev_flag:
          - ""
          - "--release"
    steps:
      - uses: actions/checkout@v2
      - name: rustup install
        run: |
          rustup toolchain update --no-self-update ${{ matrix.rustup_channel }}
          rustup default ${{ matrix.rustup_channel }}
          rustup component add clippy rustfmt
      - name: Rust check
        run: cargo check --all ${{ matrix.dev_flag }}
      - name: Clippy lint
        run: cargo clippy --all
      - name: Rust test
        run: cargo test --all ${{ matrix.dev_flag }}
